// Turkish labels for audit actions (AuditAction in src/server/services/audit.ts).
export const AUDIT_ACTION_LABEL: Record<string, string> = {
  "class.create": "Sınıf oluşturuldu",
  "class.update": "Sınıf güncellendi",
  "class_goal.set": "Sınıf hedefi konuldu",
  "class_goal.end": "Sınıf hedefi bitirildi",
  "student.create": "Öğrenci eklendi",
  "student.update": "Öğrenci güncellendi",
  "student.character_change": "Karakter türü değişti",
  "student.delete": "Öğrenci verileri silindi",
  "invite.create": "Davet kodu oluşturuldu",
  "invite.revoke": "Davet kodu iptal edildi",
  "parent.link": "Veli bağlandı",
  "behavior_type.create": "Davranış tipi eklendi",
  "behavior_type.update": "Davranış tipi güncellendi",
  "behavior.give": "Puan verildi",
  "behavior.give_home": "Ev davranışı işaretlendi",
  "behavior.undo": "Puan geri alındı",
  "behavior.delete": "Puan silindi",
  "curriculum.create": "Müfredat öğesi eklendi",
  "curriculum.update": "Müfredat öğesi güncellendi",
  "curriculum.archive": "Müfredat öğesi arşivlendi",
  "curriculum.restore": "Müfredat öğesi geri getirildi",
  "curriculum.reorder": "Müfredat sırası değişti",
  "progress.set": "İlerleme değişti",
  "progress.bulk_set": "Toplu ilerleme değişti",
  "character.thresholds_update": "Seviye eşikleri değişti",
  "character_type.update": "Karakter türü güncellendi",
  "message.create": "Mesaj gönderildi",
  "message.delete": "Mesaj silindi",
  "deletion.request": "Silme talebi",
  "deletion.reject": "Silme talebi reddedildi",
  "user.delete": "Hesap silindi",
  "data.export": "Veri dışa aktarıldı",
};

export const auditActionLabel = (action: string) => AUDIT_ACTION_LABEL[action] ?? action;
